trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GOOS: 'linux'
  GOARCH: 'amd64'
  imagePullSecret: 'secret'
  acrname: 'myacrchabbi'
  aksname: 'clusterchabbi'
  dockerregistry: 'akschabbi97'
  kubernetesserviceconnection: 'kubechabbi'
  azureserviceconnection: 'serviceconnection1'
  azureresourcegroup: 'akschabbi'
  azureSubscriptionid: '8fdfcd42-cb6a-4f09-bd1d-984a332c84b1'



steps:

- task: TerraformCLI@0
  displayName: 'check terraform version'
  inputs:
    command: version

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: ‘Install Terraform 1.3.6’
  inputs:
    terraformVersion: 1.3.6

- task: TerraformTaskV4@4
  inputs:
     provider: 'azurerm'
     command: 'init'
     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
     backendServiceArm: 'serviceconnection1'
     backendAzureRmResourceGroupName: 'stgchabbi'
     backendAzureRmStorageAccountName: 'stgchabbi1'
     backendAzureRmContainerName: 'tfcontainer'
     backendAzureRmKey: '5aXtOUjYuHwdbLsFHEFsbY8jxFePPzy/RRsQcBl0HbOyPamfVh8V+MI+xofG8Ohl1KT9A5A7cJQA+ASt+/0PLQ=='
     StorageContainerName: 'tfcontainer'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'serviceconnection1'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'serviceconnection1'

# - task: TerraformCLI@0
#   inputs:
#     command: 'init'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
#     commandOptions: '-input=true'
#     backendType: 'azurerm'
#     backendServiceArm: 'serviceconnection1'
#     backendAzureRmSubscriptionId: '8fdfcd42-cb6a-4f09-bd1d-984a332c84b1'
#     backendAzureRmResourceGroupName: 'stgchabbi'
#     backendAzureRmStorageAccountName: 'stgchabbi1'
#     backendAzureRmContainerName: 'tfcontainer'
#     backendAzureRmKey: 'terraform\terraform.tfstate'
#     allowTelemetryCollection: true

# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
#     commandOptions: '-auto-approve'
#     environmentServiceNameAzureRM: 'serviceconnection1'

# - task: Terraform@2
#   inputs:
#     TemplatePath: 'terraform/**'
#     Arguments: 'apply'
#     backendServiceArm: 'serviceconnection1'
#     InstallTerraform: true
#     UseAzureSub: true
#     ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
#     ConnectedServiceNameARM: 'serviceconnection1'
#     ManageState: true
#     SpecifyStorageAccount: true
#     StorageAccountResourceGroup: 'stgchabbi'
#     StorageAccountRM: 'stgchabbi1'





# - task: TerraformCLI@0
#   displayName: install terraform
#   inputs:
#     terraformVersion: '1.4.2'

# - task: TerraformTaskV4@0
#   displayName: 'terraform init'
#   inputs:
#     provider: 'azurerm'
#     command: init
#     backendType: azurerm
#     workingDirectory: $(System.DefaultWorkingDirectory)/terraform/
#     # providerAzureRmSubscriptionId: $(azureSubscriptionid)
#     runAzLogin: true
#     backendServiceArm: $(azureserviceconnection)
#     backendAzureRmResourceGroupName: 'stgchabbi'
#     backendAzureRmStorageAccountName: 'storagechabbi'
#     backendAzureRmContainerName: 'chabbiblob'
#     backendAzureRmKey: $(System.DefaultWorkingDirectory)/terraform/terraform.tfstate

# - task: TerraformTaskV4@0
#   displayName: Terraform Plan
#   inputs:
#     # provider: 'azurerm'
#     command: 'plan'
#     workingDirectory: $(System.DefaultWorkingDirectory)/terraform/
#     environmentServiceNameAzureRM: $(azureserviceconnection)

# - task: TerraformTaskV4@0
#   displayName: Terraform Apply
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: $(System.DefaultWorkingDirectory)/terraform/
#     environmentServiceNameAzureRM: $(azureserviceconnection)

# - task: TerraformTaskV1@0
#   displayName: 'Init Terraform'
#   inputs:
#     provider: 'azurerm'
#     command: 'init'
#     commandOptions: '-input=false -backend=false'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
#     backendserviceArm: '$(System.DefaultWorkingDirectory)\Users\nis-bilal\http_echo\http-echo\terraform\providers.tf'
#     backendAzureRmResourceGroupName: 'N/A'
#     backendAzureRmStorageAccountName: 'N/A'
#     backendAzureRmContainerName: 'N/A'
#     backendAzureRmKey: 'N/A'
# - task: TerraformTaskV1@0
#   displayName: 'Validate Terraform'
#   inputs:
#     provider: 'azurerm'
#     command: 'validate'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
#     # backendserviceArm: '$(System.DefaultWorkingDirectory)/terraform'
# - task: TerraformTaskV1@0
#   displayName: 'Apply Terraform'
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
#     # backendserviceArm: '$(System.DefaultWorkingDirectory)/terraform'
#     azureserviceconnection: '$(azureserviceconnection)'

- task: GoTool@0
  inputs:
    version: '1.19'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o $(Build.BinariesDirectory) '
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: CopyFiles@2
  inputs:
    Contents: |
      $(System.DefaultWorkingDirectory)/manifest/deployment.yml
      $(System.DefaultWorkingDirectory)/manifest/service.yml
    TargetFolder: '$(Pipeline.Workspace)/s/manifest'

- task: Docker@2
  displayName: Build Docker image
  inputs:
    containerRegistry: $(dockerregistry)
    repository: '$(acrname)/http-echo'
    command: 'build'
    Dockerfile: 'Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)'
    tags: |
      $(Build.BuildId)
      latest


- task: Docker@2
  displayName: Push Docker image to ACR
  inputs:
    containerRegistry: $(dockerregistry)
    repository: '$(acrname)/http-echo'
    command: 'push'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- task: KubernetesManifest@0
  displayName: Create imagePullSecret
  inputs:
    action: createSecret
    secretName: $(imagePullSecret)
    dockerRegistryEndpoint: $(dockerregistry)
    kubernetesServiceConnection: $(kubernetesserviceconnection)
    namespace: 'default'

- script: |
   envsubst < $(Pipeline.Workspace)/s/manifest/deployment.yml.template >  $(Pipeline.Workspace)/s/manifest/deployment.yml
  displayName: 'Script task'

- task: KubernetesManifest@0
  displayName: Delete Kubernetes cluster
  inputs:
    action: delete
    kubernetesServiceConnection: '$(kubernetesserviceconnection)'
    namespace: 'default'
    rolloutStatusTimeout: 5
    arguments: deployment web

- task: KubernetesManifest@0
  displayName: Deploy to Kubernetes cluster
  inputs:
    action: deploy
    kubernetesServiceConnection: '$(kubernetesserviceconnection)'
    namespace: 'default'
    rolloutStatusTimeout: 5
    manifests: |
      $(Pipeline.Workspace)/s/manifest/deployment.yml
      $(Pipeline.Workspace)/s/manifest/service.yml
    imagePullSecrets: |
      $(imagePullSecret)
    containers: |
      $(acrname)/http-echo:$(Build.BuildId)


- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
    checkLatestVersion: true

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureserviceconnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group $(azureresourcegroup) --name $(aksname)
      helm repo add haproxytech https://haproxytech.github.io/helm-charts
      helm repo update
      helm upgrade --install kubernetes-ingress haproxytech/kubernetes-ingress --create-namespace --namespace haproxy-controller --set controller.service.type=LoadBalancer
  displayName: Deploy HA-Proxy-ingress

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: $(azureserviceconnection)
    azureResourceGroup: $(azureresourcegroup)
    kubernetesCluster: $(aksname)
    kubernetesServiceEndpoint: $(kubernetesserviceconnection)
    command: 'get'
    arguments: 'services --namespace haproxy-controller kubernetes-ingress'
    outputFormat: jsonpath={.status.loadBalancer.ingress[0].ip} ##show the external ip in a proper way
  displayName: 'Get external IP'
  name: GetExternalIP


- task: Bash@3
  inputs: 
    targetType: 'inline'
    script: |
      curl -v http://${GETEXTERNALIP_KUBECTLOUTPUT}
  displayName: 'Curl Test'

- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop